on:
  push:
    branches:
      - main
      - dev-2.0
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Set up Python virtual environment
        run: |
          python -m venv .venv

      - name: Activate virtual environment
        run: |
          .\.venv\Scripts\Activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Install FFmpeg
        run: |
          winget install --id Gyan.FFmpeg -e

      - name: Verify FFmpeg installation
        run: |
          ffmpeg -version

      - name: Compile with Nuitka
        run: |
          nuitka `
          --enable-plugin=pyqt5 `
          --include-data-files="ffmpeg.exe=C:/Windows/System32/ffmpeg.exe" `
          --include-data-files="pytranscriber/gui/*.qm=pytranscriber/gui/" `
          --include-data-dir="venv/lib/python3.8/site-packages/whisper/assets=whisper/assets" `
          main.py `
          --onefile `
          --disable-console

      - name: Upload built executable
        uses: actions/upload-artifact@v4
        with:
          name: pyTranscriber
          path: ./dist/main.exe  # Adjust this path if Nuitka outputs elsewhere

  download:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download built executable
        uses: actions/download-artifact@v4
        with:
          name: pyTranscriber
          path: ./output

      - name: List downloaded files
        run: dir ./output
