on:
  push:
    branches:
      - main
      - dev-2.0
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

     - name: Compile with Nuitka
      run: |
        nuitka `
        --enable-plugin=pyqt5 `
        --include-data-files="ffmpeg.exe=./" `
        --include-data-files="pytranscriber/gui/*.qm=pytranscriber/gui/" `
        --include-data-dir="venv/lib/python3.8/site-packages/whisper/assets=whisper/assets" `
        main.py `
        --onefile `
        --disable-console

      - name: List files in dist
        run: dir ./dist  # Ensure the .exe file is in the dist folder

      - name: Upload built executable
        uses: actions/upload-artifact@v4
        with:
          name: pyTranscriber
          path: ./dist/main.exe  # Adjust this path if Nuitka outputs somewhere else

  download:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download built executable
        uses: actions/download-artifact@v4
        with:
          name: pyTranscriber  # This should match the upload name
          path: ./output

      - name: List downloaded files
        run: dir ./output  # Verify the download path
